### ISSUE TITLE
Amount of delegation is not display on the page

### ISSUE THREAD

**Issue by antoineherzog** [iov-one/big-dipper#10]
<img width="1440" alt="Capture d’écran 2020-09-08 à 6 55 46 PM" src="https://user-images.githubusercontent.com/13095/92505975-09b77e00-f205-11ea-8e7b-24eca731b5b0.png">
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davepuchyr** [comment]
Closed via https://github.com/iov-one/big-dipper/pull/9.
